export const campaignAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_cid", type: "string", internalType: "string" },
      { name: "_goal", type: "uint256", internalType: "uint256" },
      { name: "_daysToend", type: "uint256", internalType: "uint256" },
      { name: "_owner", type: "address", internalType: "address" },
      {
        name: "_campaignType",
        type: "uint8",
        internalType: "enum Campaign.CampaignType",
      },
    ],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "deposite",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "endCampaign",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCId",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCampiagnInfo",
    inputs: [],
    outputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "bool", internalType: "bool" },
      { name: "", type: "bool", internalType: "bool" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint8", internalType: "enum Campaign.CampaignType" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDonarBalance",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getGoal",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalDonation",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasCampaignSucceed",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalDonars",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawByDoner",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CampaginEnded",
    inputs: [
      { name: "isSuccess", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DonationReceived",
    inputs: [
      {
        name: "donor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "CampaignFailed", inputs: [] },
  { type: "error", name: "CampaignHasEnded", inputs: [] },
  { type: "error", name: "CampaignStillRunning", inputs: [] },
  { type: "error", name: "NotAutorized", inputs: [] },
];
